import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import FileControllerProvider from "./lib/contexts/file-controller/index.";
import CacheControllerProvider from "./lib/contexts/cache-controller";
import PixiViewProvider from "./features/pixi-view/context";

import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PixiViewProvider>
          <CacheControllerProvider>
            <FileControllerProvider>
              {children}
            </FileControllerProvider>
          </CacheControllerProvider>
        </PixiViewProvider>
      </body>
    </html>
  );
}
